services:
  postgres:
    image: postgres:17.2
    container_name: postgres-task-management
    ports:
      - "5432:5432"
    volumes:
      - task_management_postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      DB_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  task_management_postgres_data:
    driver: local
